name: My First Workflow

on: push

jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Welcome Message
          run: echo "Hiiiiiiiiiiiiiiiiiiiiiii"

        - name: List files
          run: ls

        - name: Read files
          run: cat README.md
               
